
## First create the compiler image by running
##   docker build --file Dockerfile.nightly --tag bench_rust_nightly .

# Make sure to change the version/date everywhere (I couldn't get ARG to work), i.e. `rustup default`
FROM bench_rust_nightly

# Copy Cargo file only to compile dependencies in a separate layer
COPY Cargo.toml ./Cargo.toml
COPY Cargo.lock ./Cargo.lock

# Create a dummy main file so compiling dependencies works
RUN mkdir src && printf "fn main() {}" > src/main.rs

# Build the dependencies, to have a cached layer
RUN cargo build --quiet --all --release

# Copy the code
COPY /src ./src

# Compile the application
RUN cargo build --quiet --all --release
