
## This Dockerfile.cache sets up the nightly compiler, and should not be part of the benchmark

FROM rust:1.33.0 AS bench_rust_nightly

ENV RUST_BACKTRACE 1
ENV RUSTFLAGS "-D warnings"

# Cache cargo dependencies
ENV CARGO_HOME /cache/dockerout/cargo
ENV CARGO_TARGET_DIR /cache/dockerout/target

ENV RUST_VERSION "nightly-2019-05-15"

# Nightly (I dont know why version number doesnt work)
RUN rustup install "$RUST_VERSION"
RUN rustup default "$RUST_VERSION"
